### ISSUE TITLE
[Feat]aws connect

### ISSUE THREAD

**Issue by Byeongsoo-Min** [TeamGoodGood/RelayNovel-server#6]
**Issue : Feature**
aws에 데이터베이스를 연결하고, aws 인스턴스의 탄력적 ip 주소를 연동시켜 서버 상에서 앱을 구동시켜야 합니다.

**Description**
settings.py를 변경예정에 있습니다.
서버에 계속 접속해 있을 예정입니다. 혹시 모를 불상사에 대비해 들어가실 때 말 부탁드립니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] aws 인스턴스 서버 열기
- [x] aws 인스턴스 서버 기초 설정하기
- [x] aws 인스턴스 탄력적 ip 받아오기
- [x] aws 인스턴스 상에 가상환경을 만들고, 기초 환경 설정하기
- [x] #7
